# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-lambdas:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.gradle" }}
          - v2-dependencies-

      - run: ./gradlew --no-daemon :lambda:build

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: .
          paths:
            - lambda/build/distributions

  test-event-store:
    machine:
      docker_layer_caching: true

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.gradle" }}-{{ checksum "event-store/build.gradle" }}
          - v2-dependencies-

      - run: ./gradlew --no-daemon --info :event-store:test

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}-{{ checksum "event-store/build.gradle" }}

      - store_test_results:
          path: event-store/build/test-results

  deploy-lambdas:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-toplevel-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-toplevel-{{ .Branch }}
            - yarn-packages-toplevel-master

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-toplevel-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

      - attach_workspace:
          at: .

      - run:
          name: Deploying Lambdas
          command: yarn run serverless deploy -v

  build-frontend:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo/frontend

    environment:
      TERM: dumb

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-frontend-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-frontend-{{ .Branch }}
            - yarn-packages-frontend-master

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-frontend-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

      - run: yarn run webpack

      - persist_to_workspace:
          root: .
          paths:
            - site

  deploy-frontend:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo/frontend

    environment:
      TERM: dumb

    steps:
      - checkout:
          path: ~/repo

      - attach_workspace:
          at: .

      - run:
          name: Deploying Frontend
          command: ./scripts/deploy-gh-pages.sh

deploy-lambdas-job-defaults: &deploy-lambdas-job-defaults
  requires:
    - build-lambdas
    - test-event-store
  filters:
    branches:
      only: master

deploy-frontend-job-defaults: &deploy-frontend-job-defaults
  requires:
    - build-frontend
  filters:
    branches:
      only: master

workflows:
  version: 2

  backend-only:
    jobs:
      - test-event-store
      - build-lambdas
      - *deploy-lambdas-job-defaults

  frontend-only:
    jobs:
      - build-frontend
      - deploy-frontend:
          <<: *deploy-frontend-job-defaults

  backend-and-frontend:
    jobs:
      - test-event-store
      - build-lambdas
      - *deploy-lambdas-job-defaults
      - build-frontend
      - deploy-frontend:
          <<: *deploy-frontend-job-defaults
          requires:
            - deploy-lambdas
            - build-frontend

